import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const gratoFont = localFont({
	src: [
		{
			path: './fonts/gratogrotesk-regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/gratogrotesk-bold.otf',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-gratofont',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${gratoFont.variable} antialiased`}>{children}</body>
		</html>
	)
}
